<?php

namespace App\Services;

use Firebase\JWT\JWT;
use Firebase\JWT\Key;

/**
 * JWT + refresh-token utilities.
 * - Access token: short-lived JWT (HS256), 15 minutes
 * - Refresh token: opaque random string (48 bytes), stored sha256-hashed in MySQL
 * - Passwords: bcrypt with 12 salt rounds
 */
class TokenService
{
    public const ACCESS_TOKEN_TTL = 900;          // seconds (15 min)
    public const REFRESH_TOKEN_TTL_DAYS = 7;

    private static function secret(): string
    {
        $secret = env('JWT_SECRET', '');
        if ($secret === '') {
            throw new \RuntimeException('JWT_SECRET is not configured');
        }
        return $secret;
    }

    /** Sign an HS256 access token. */
    public static function signAccess(int $sub, string $role, string $name): string
    {
        $now = time();
        $payload = [
            'sub'  => $sub,
            'role' => $role,
            'name' => $name,
            'iat'  => $now,
            'exp'  => $now + self::ACCESS_TOKEN_TTL,
        ];
        return JWT::encode($payload, self::secret(), 'HS256');
    }

    /**
     * Verify an access token. Returns array payload or throws.
     */
    public static function verifyAccess(string $token): array
    {
        JWT::$leeway = 30;
        return (array) JWT::decode($token, new Key(self::secret(), 'HS256'));
    }

    /** Create opaque refresh token + its sha256 hash for storage. */
    public static function createRefreshToken(): array
    {
        $token = bin2hex(random_bytes(48));
        return ['token' => $token, 'hash' => hash('sha256', $token)];
    }

    public static function hashToken(string $token): string
    {
        return hash('sha256', $token);
    }

    /** Hash a plain password with bcrypt (12 rounds). */
    public static function hashPassword(string $plain): string
    {
        return password_hash($plain, PASSWORD_BCRYPT, ['cost' => 12]);
    }

    /**
     * Verify a plain password against a stored bcrypt hash.
     * Uses PHP's native password_verify, which accepts $2a$/$2b$/$2y$
     * hashes (including those generated by Node's bcryptjs).
     */
    public static function verifyPassword(string $plain, string $hash): bool
    {
        return password_verify($plain, $hash);
    }
}
