import { Profile, SuccessStory, BlogArticle } from './types';

export const mockProfiles: Profile[] = [
  {
    id: 'p1',
    name: 'Aishwarya Iyer',
    gender: 'Bride',
    age: 26,
    height: "5'4\"",
    religion: 'Hindu',
    caste: 'Iyer',
    subCaste: 'Vadama',
    motherTongue: 'Tamil',
    profession: 'Software Engineer',
    education: 'M.S. in Computer Science',
    location: { city: 'Chennai', state: 'Tamil Nadu', country: 'India' },
    salary: '₹22 LPA',
    diet: 'Veg',
    manglik: 'No',
    horoscopeNeeded: true,
    starSign: 'Aries',
    familyValues: 'Moderate',
    lifestyle: 'Modern',
    bio: 'A warm, ambitious software professional who loves classical Carnatic vocal music, traditional Bharatanatyam dance, and exploring modern cafes. Seeking a respectful, supportive companion who values our deep South Indian heritage and shares a progressive mindset.',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=400&h=400',
    verified: true,
    contactNumber: '+91 98765 43210',
    birthDate: '2000-04-12',
    birthTime: '06:45 AM',
    birthPlace: 'Chennai, Tamil Nadu',
    rashi: 'Mesha (Aries)',
    nakshatra: 'Aswini',
    gotra: 'Kashyapa',

    // Comprehensive Fields
    basicInfo: {
      profileCreatedBy: 'Parents',
      firstName: 'Aishwarya',
      lastName: 'Iyer',
      displayName: 'Aishwarya I.',
      weight: '54 kg',
      bodyType: 'Slim',
      complexion: 'Fair',
      bloodGroup: 'O+ve',
      maritalStatus: 'Never Married',
      children: 'None',
      disabilityStatus: 'None',
      languagesKnown: ['Tamil', 'English', 'Hindi', 'Sanskrit'],
      nationality: 'Indian',
      citizenship: 'Indian'
    },
    contactInfo: {
      mobileNumber: '+91 98765 43210',
      whatsAppNumber: '+91 98765 43210',
      email: 'aishwarya.iyer@soulmate.in',
      district: 'Chennai',
      area: 'Adyar',
      pinCode: '600020',
      currentAddress: 'New No. 14, 3rd Main Road, Kasturiba Nagar, Adyar, Chennai',
      permanentAddress: 'New No. 14, 3rd Main Road, Kasturiba Nagar, Adyar, Chennai'
    },
    photos: {
      mainProfilePhoto: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=400&h=400',
      coverPhoto: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=1200&h=400',
      fullLengthPhoto: 'https://images.unsplash.com/photo-1621184455862-c163dfb30e0f?auto=format&fit=crop&q=80&w=500&h=800',
      traditionalDressPhoto: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=400&h=400',
      casualPhoto: 'https://images.unsplash.com/photo-1594744803329-e58b31de215f?auto=format&fit=crop&q=80&w=400&h=400',
      familyPhoto: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&q=80&w=600&h=400',
      album: [
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=400&h=400',
        'https://images.unsplash.com/photo-1621184455862-c163dfb30e0f?auto=format&fit=crop&q=80&w=500&h=800'
      ],
      privateAlbum: false,
      verificationSelfie: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=200&h=200'
    },
    aboutMe: {
      personality: ['Ambitious', 'Warm-hearted', 'Artistic', 'Family-oriented', 'Thoughtful'],
      interests: ['Vedic Astrology', 'Classical Music', 'Nature Walks', 'Specialty Coffee', 'Heritage Preservation'],
      hobbies: ['Carnatic Vocal Singing', 'Bharatanatyam Dance', 'Kolam Designing', 'Gourmet Cooking', 'Travel Blogging'],
      lifeGoals: 'To excel as an AI professional while nurturing a peaceful, spiritually grounded family life centered on mutual growth.',
      expectations: 'Looking for a respectful, well-educated Tamil Brahmin partner with progressive views, who values cultural values and treats marriage as a collaborative partnership.'
    },
    religiousInfo: {
      templeVisits: 'Weekly visits (specifically to Kapaleeshwarar Temple on Fridays)',
      spiritualBeliefs: 'Deep faith in Advaita Vedanta philosophy; practices daily meditation and chanting.',
      religiousPractices: 'Observes major traditional fasts (Pradosham, Ekadashi), performs Lakshmi Puja.'
    },
    educationDetails: {
      highestQualification: 'Master of Science',
      degree: 'M.S. in Computer Science',
      specialization: 'Artificial Intelligence & Machine Learning',
      college: 'College of Engineering, Guindy (CEG) & Georgia Tech',
      university: 'Anna University & Georgia Institute of Technology',
      graduationYear: 2022,
      additionalQualifications: ['PG Diploma in Sanskrit Studies', 'Prathama in Carnatic Music'],
      certifications: ['AWS Certified Solutions Architect', 'Google Professional ML Engineer'],
      academicAchievements: ['University Gold Medalist (Anna University)', 'Deans Fellowship Award at Georgia Tech']
    },
    occupationDetails: {
      employmentType: 'Private Sector',
      occupation: 'Senior Machine Learning Engineer',
      companyName: 'Microsoft R&D India',
      designation: 'Senior SDE - AI Platforms',
      industry: 'Information Technology',
      experience: '4 Years',
      annualIncome: '₹22 LPA',
      monthlyIncome: '₹1.8 Lakhs',
      officeLocation: 'DLF Cybercity, Chennai',
      workingCountry: 'India',
      workVisa: 'Not Applicable',
      businessDetails: 'None'
    },
    familyDetails: {
      father: {
        name: 'V. Sundaramurthy Iyer',
        occupation: 'Retired Senior Director',
        education: 'B.Tech IIT Madras, MBA IIM Ahmedabad',
        business: 'Not Applicable',
        annualIncome: 'Pension & Investments',
        status: 'Alive'
      },
      mother: {
        name: 'Savitri Sundaramurthy',
        occupation: 'Homemaker & Carnatic Music Teacher',
        education: 'B.A. in Music (Madras University)',
        status: 'Working'
      },
      siblings: {
        brothers: 1,
        marriedBrothers: 1,
        sisters: 0,
        marriedSisters: 0
      },
      familyType: 'Nuclear',
      familyStatus: 'Upper Middle Class',
      nativePlace: 'Thanjavur, Tamil Nadu',
      familyWealth: 'Owns 3 residential properties in Chennai and agricultural ancestral holdings in Thanjavur.',
      ownHouse: true,
      familyBusiness: 'None'
    },
    habits: {
      smoking: 'No',
      drinking: 'No',
      fitness: ['Yoga', 'Classical Dance', 'Evening Jogging'],
      gym: false,
      yoga: true,
      pets: 'Fish aquarium at home',
      travel: 'Loves heritage tours, spiritual trails in South India, and international mountain destinations.',
      drivingLicense: true
    },
    physicalAppearance: {
      skinTone: 'Fair',
      hairColor: 'Black / Long',
      eyeColor: 'Dark Brown',
      beard: false,
      bodyType: 'Slim'
    },
    assets: {
      ownHouse: true,
      apartment: true,
      villa: false,
      land: true,
      farm: false,
      commercialProperty: false,
      car: 'Honda City',
      bike: 'None',
      investments: 'Mutual Funds, Equity Shares, Fixed Deposits',
      gold: '120 Sovereigns (Ancestral and self)',
      savings: 'High'
    },
    partnerPreferences: {
      ageRange: '27 - 31 Years',
      height: "5'8\" - 6'2\"",
      maritalStatus: 'Never Married',
      religion: 'Hindu',
      caste: 'Tamil Brahmin (Iyer or Iyengar)',
      subCaste: 'Vadama, Brahacharanam, Astasahasram',
      qualification: 'Post Graduate or Above',
      degree: 'M.S., M.Tech, MBA, MD, PhD, or CA',
      occupation: 'Tech professional, Doctor, Banker, or Civil Servant',
      income: '₹25 LPA+',
      diet: 'Pure Vegetarian',
      smoking: 'No',
      drinking: 'No',
      country: 'India, USA, or Canada',
      state: 'Tamil Nadu, Karnataka, Telangana',
      city: 'Chennai, Bangalore, Hyderabad, San Francisco, New York',
      star: 'Aswini, Krithika, Rohini, Mrigashasira, Hastham, Swathi',
      rasi: 'Mesha, Vrishabha, Mithuna, Kanya, Thula',
      dosham: 'No Sevvai Dosham / Manglik'
    },
    aiCompatibility: {
      personalityScore: 92,
      lifestyleMatch: 95,
      familyValuesMatch: 90,
      educationMatch: 94,
      careerMatch: 88,
      horoscopeMatch: 85,
      overallMatch: 91
    },
    verification: {
      mobileVerified: true,
      emailVerified: true,
      aadhaarVerified: true,
      panVerified: true,
      passportVerified: true,
      employmentVerified: true,
      educationVerified: true,
      photoVerified: true
    },
    privacySettings: {
      hideMobile: true,
      hideEmail: true,
      hideIncome: false,
      hidePhotos: false,
      hideHoroscope: false,
      hideFamilyDetails: false,
      privateProfile: false
    },
    activity: {
      lastLogin: 'Today, 10:15 AM',
      onlineStatus: 'Online',
      profileCompletion: 95,
      profileViews: 342,
      interestsSent: 18,
      interestsReceived: 45,
      shortlistedBy: 56
    },
    premiumFeatures: {
      premiumMember: true,
      profileBoost: true,
      spotlightProfile: true,
      readReceipts: true,
      unlimitedChat: true,
      unlimitedContactView: true,
      videoCallEnabled: true
    },
    aiProfileInsights: {
      profileStrength: 'Excellent',
      missingInformation: ['No missing mandatory info.'],
      suggestedImprovements: ['Add a family video intro', 'Provide details on sibling specialization'],
      recommendedPhotos: ['Outdoor profile shoot recommended for better profile visibility'],
      matchProbability: 'High (88%)',
      compatibilityAnalysis: 'Aishwarya has a highly balanced chart reflecting excellence in career (AI domain) and traditional accomplishments (Carnatic & Bharatanatyam), indicating high compatibility with structured, progressive corporate professionals.'
    },
    documents: {
      aadhaarCard: true,
      panCard: true,
      passport: true,
      degreeCertificate: true,
      salarySlip: true,
      horoscopePdf: true
    }
  },
  {
    id: 'p2',
    name: 'Karthik Krishnan',
    gender: 'Groom',
    age: 28,
    height: "5'11\"",
    religion: 'Hindu',
    caste: 'Iyengar',
    subCaste: 'Vadakalai',
    motherTongue: 'Tamil',
    profession: 'Management Consultant',
    education: 'MBA - IIM Bangalore',
    location: { city: 'Bengaluru', state: 'Karnataka', country: 'India' },
    salary: '₹35 LPA',
    diet: 'Veg',
    manglik: 'No',
    horoscopeNeeded: true,
    starSign: 'Leo',
    familyValues: 'Traditional',
    lifestyle: 'Balanced',
    bio: 'Traditional yet modern management consultant based in Bengaluru. Grounded in Vedic principles, I enjoy playing the mridangam, running weekend marathons, and reading ancient history. Looking for someone sweet, values-driven, and family-oriented who appreciates traditional South Indian lifestyle.',
    image: 'https://images.unsplash.com/photo-1605135738135-7f982ca32f97?auto=format&fit=crop&q=80&w=400&h=400',
    verified: true,
    contactNumber: '+91 91234 56789',
    birthDate: '1998-08-15',
    birthTime: '11:15 AM',
    birthPlace: 'Bangalore, Karnataka',
    rashi: 'Simha (Leo)',
    nakshatra: 'Poorvaphalguni',
    gotra: 'Srivatsa',

    // Comprehensive Fields
    basicInfo: {
      profileCreatedBy: 'Self',
      firstName: 'Karthik',
      lastName: 'Krishnan',
      displayName: 'Karthik K.',
      weight: '76 kg',
      bodyType: 'Athletic',
      complexion: 'Wheatish',
      bloodGroup: 'B+ve',
      maritalStatus: 'Never Married',
      children: 'None',
      disabilityStatus: 'None',
      languagesKnown: ['Tamil', 'Kannada', 'English', 'Hindi'],
      nationality: 'Indian',
      citizenship: 'Indian'
    },
    contactInfo: {
      mobileNumber: '+91 91234 56789',
      whatsAppNumber: '+91 91234 56789',
      email: 'karthik.krishnan@consulting.in',
      district: 'Bangalore Urban',
      area: 'Jayanagar',
      pinCode: '560041',
      currentAddress: '32/A, 5th Main Road, 4th T Block, Jayanagar, Bangalore',
      permanentAddress: '32/A, 5th Main Road, 4th T Block, Jayanagar, Bangalore'
    },
    photos: {
      mainProfilePhoto: 'https://images.unsplash.com/photo-1605135738135-7f982ca32f97?auto=format&fit=crop&q=80&w=400&h=400',
      coverPhoto: 'https://images.unsplash.com/photo-1513829096999-4978602297af?auto=format&fit=crop&q=80&w=1200&h=400',
      fullLengthPhoto: 'https://images.unsplash.com/photo-1614283233556-f35b0c801ef1?auto=format&fit=crop&q=80&w=500&h=800',
      traditionalDressPhoto: 'https://images.unsplash.com/photo-1605135738135-7f982ca32f97?auto=format&fit=crop&q=80&w=400&h=400',
      casualPhoto: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=crop&q=80&w=400&h=400',
      familyPhoto: 'https://images.unsplash.com/photo-1542037104857-ffbb0b9155fb?auto=format&fit=crop&q=80&w=600&h=400',
      album: [
        'https://images.unsplash.com/photo-1605135738135-7f982ca32f97?auto=format&fit=crop&q=80&w=400&h=400',
        'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=crop&q=80&w=400&h=400'
      ],
      privateAlbum: false,
      verificationSelfie: 'https://images.unsplash.com/photo-1605135738135-7f982ca32f97?auto=format&fit=crop&q=80&w=200&h=200'
    },
    aboutMe: {
      personality: ['Grounded', 'Analytical', 'Energetic', 'Traditional', 'Intellectual'],
      interests: ['Vedic Philosophy', 'Marathons', 'Ancient History', 'Temple Music', 'Stock Markets'],
      hobbies: ['Mridangam Playing', 'Running', 'Sanskrit Literature Reading', 'Temple Architecture Exploration', 'Numismatics'],
      lifeGoals: 'To build a global business consulting reputation while leading a devout, peaceful life centered on community development and family warmth.',
      expectations: 'Seeking a kind, cultured, and family-oriented South Indian bride (preferably vegetarian) who values traditional family setups and has her own creative or academic pursuits.'
    },
    religiousInfo: {
      templeVisits: 'Daily visits (specifically Sri Ranganatha Swamy Temple / Malleshwaram Temple)',
      spiritualBeliefs: 'Devout Sri Vaishnavism follower; actively studies works of Ramanuja and Desika.',
      religiousPractices: 'Performs Sandhyavandanam twice daily, participates in annual Brahmotsavam.'
    },
    educationDetails: {
      highestQualification: 'Master of Business Administration',
      degree: 'MBA (Post Graduate Diploma in Management)',
      specialization: 'Strategy & Finance',
      college: 'Indian Institute of Management Bangalore (IIM-B)',
      university: 'IIM Bangalore',
      graduationYear: 2021,
      additionalQualifications: ['B.Tech in Mechanical Engineering (NIT Trichy)'],
      certifications: ['Chartered Financial Analyst (CFA) Level II Candidate'],
      academicAchievements: ['Director\'s Merit List at IIM-B', 'Aditya Birla Scholar']
    },
    occupationDetails: {
      employmentType: 'Private Sector',
      occupation: 'Management Consultant / Associate Partner',
      companyName: 'McKinsey & Company',
      designation: 'Engagement Manager - Public Sector & Strategy',
      industry: 'Management Consulting',
      experience: '5 Years',
      annualIncome: '₹35 LPA',
      monthlyIncome: '₹2.7 Lakhs',
      officeLocation: 'MG Road, Bangalore',
      workingCountry: 'India',
      workVisa: 'H1-B Approved (Previously worked in Boston)',
      businessDetails: 'None'
    },
    familyDetails: {
      father: {
        name: 'Dr. K. Krishnan Iyengar',
        occupation: 'Senior Cardiologist & Professor',
        education: 'MD, DM (Cardiology) - JIPMER',
        business: 'Owns Sri Krishna Heart Clinic, Bangalore',
        annualIncome: '₹50 LPA+',
        status: 'Alive'
      },
      mother: {
        name: 'Srimathi Rukmini Krishnan',
        occupation: 'Homemaker & Sanskrit Scholar',
        education: 'Ph.D. in Sanskrit Literature (Madras University)',
        status: 'Working'
      },
      siblings: {
        brothers: 0,
        marriedBrothers: 0,
        sisters: 1,
        marriedSisters: 1
      },
      familyType: 'Joint / Close-knit Nuclear',
      familyStatus: 'Rich / Upper Class',
      nativePlace: 'Srirangam, Tamil Nadu',
      familyWealth: 'Multiple commercial properties in Bangalore, ancestral home in Srirangam, high portfolio of equity investments.',
      ownHouse: true,
      familyBusiness: 'Healthcare Clinic chain'
    },
    habits: {
      smoking: 'No',
      drinking: 'No',
      fitness: ['Marathon training', 'Yoga', 'Mridangam practice'],
      gym: true,
      yoga: true,
      pets: 'None',
      travel: 'Enjoys spiritual excursions, running marathons in European cities, hiking Western Ghats.',
      drivingLicense: true
    },
    physicalAppearance: {
      skinTone: 'Wheatish',
      hairColor: 'Black / Crop cut',
      eyeColor: 'Black',
      beard: true,
      bodyType: 'Athletic'
    },
    assets: {
      ownHouse: true,
      apartment: true,
      villa: true,
      land: true,
      farm: false,
      commercialProperty: true,
      car: 'Audi A4',
      bike: 'Royal Enfield Interceptor 650',
      investments: 'Real Estate, Direct Equities, Gold Bonds',
      gold: '50 Sovereigns',
      savings: 'Very High'
    },
    partnerPreferences: {
      ageRange: '23 - 27 Years',
      height: "5'2\" - 5'8\"",
      maritalStatus: 'Never Married',
      religion: 'Hindu',
      caste: 'Iyengar or Iyer',
      subCaste: 'Vadakalai, Thenkalai, Vadama',
      qualification: 'Bachelors Degree or Above',
      degree: 'B.Tech, B.Com, MBBS, M.S, MBA, MD',
      occupation: 'Tech professional, Professional artist, Educator, Doctor',
      income: 'Flexible',
      diet: 'Pure Vegetarian',
      smoking: 'No',
      drinking: 'No',
      country: 'India (willing to relocate)',
      state: 'Karnataka, Tamil Nadu, Andhra Pradesh',
      city: 'Bangalore, Chennai, Mysore, Srirangam',
      star: 'Anuradha, Revathi, Rohini, Hastham, Chithra, Swathi',
      rasi: 'Vrishabha, Mithuna, Kanya, Thula, Vrischika',
      dosham: 'No Dosham / Suddha Jathagam'
    },
    aiCompatibility: {
      personalityScore: 94,
      lifestyleMatch: 92,
      familyValuesMatch: 95,
      educationMatch: 90,
      careerMatch: 92,
      horoscopeMatch: 88,
      overallMatch: 93
    },
    verification: {
      mobileVerified: true,
      emailVerified: true,
      aadhaarVerified: true,
      panVerified: true,
      passportVerified: true,
      employmentVerified: true,
      educationVerified: true,
      photoVerified: true
    },
    privacySettings: {
      hideMobile: true,
      hideEmail: true,
      hideIncome: false,
      hidePhotos: false,
      hideHoroscope: false,
      hideFamilyDetails: false,
      privateProfile: false
    },
    activity: {
      lastLogin: 'Active 5m ago',
      onlineStatus: 'Online',
      profileCompletion: 98,
      profileViews: 582,
      interestsSent: 25,
      interestsReceived: 96,
      shortlistedBy: 120
    },
    premiumFeatures: {
      premiumMember: true,
      profileBoost: true,
      spotlightProfile: true,
      readReceipts: true,
      unlimitedChat: true,
      unlimitedContactView: true,
      videoCallEnabled: true
    },
    aiProfileInsights: {
      profileStrength: 'Excellent',
      missingInformation: ['No missing mandatory info.'],
      suggestedImprovements: ['None'],
      recommendedPhotos: ['Add a professional consultant corporate headshot'],
      matchProbability: 'Outstanding (93%)',
      compatibilityAnalysis: 'Karthik represents a highly eligible traditional Iyengar groom profile, blending elite business credentials (IIM Bangalore, McKinsey) with deep-seated musical and Vedic values. His astrological parameters suggest stellar compatibility with brides valuing classical arts and intellectual alignment.'
    },
    documents: {
      aadhaarCard: true,
      panCard: true,
      passport: true,
      degreeCertificate: true,
      salarySlip: true,
      horoscopePdf: true
    }
  },
  {
    id: 'p3',
    name: 'Priya Subramanian',
    gender: 'Bride',
    age: 27,
    height: "5'5\"",
    religion: 'Hindu',
    caste: 'Pillai',
    subCaste: 'Saiva',
    motherTongue: 'Tamil',
    profession: 'Pediatrician',
    education: 'MD - Pediatrics',
    location: { city: 'Coimbatore', state: 'Tamil Nadu', country: 'India' },
    salary: '₹18 LPA',
    diet: 'Non-Veg',
    manglik: 'No',
    horoscopeNeeded: true,
    starSign: 'Cancer',
    familyValues: 'Moderate',
    lifestyle: 'Balanced',
    bio: 'A compassionate doctor dedicated to pediatric wellness in Coimbatore. Passionate about Bharatanatyam dance, local temples, and serene nature photography. Seeking an understanding, emotionally mature Tamil partner to walk life\'s beautiful paths together.',
    image: 'https://images.unsplash.com/photo-1610030469668-93535c17b6b3?auto=format&fit=crop&q=80&w=400&h=400',
    verified: true,
    contactNumber: '+91 98989 12345',
    birthDate: '1999-07-20',
    birthTime: '02:30 PM',
    birthPlace: 'Coimbatore, Tamil Nadu',
    rashi: 'Karka (Cancer)',
    nakshatra: 'Pushya',
    gotra: 'Bharadwaj',

    basicInfo: {
      profileCreatedBy: 'Self',
      firstName: 'Priya',
      lastName: 'Subramanian',
      displayName: 'Dr. Priya S.',
      weight: '58 kg',
      bodyType: 'Average',
      complexion: 'Medium / Wheatish',
      bloodGroup: 'A+ve',
      maritalStatus: 'Never Married',
      children: 'None',
      disabilityStatus: 'None',
      languagesKnown: ['Tamil', 'English', 'Malayalam', 'Hindi'],
      nationality: 'Indian',
      citizenship: 'Indian'
    },
    contactInfo: {
      mobileNumber: '+91 98989 12345',
      whatsAppNumber: '+91 98989 12345',
      email: 'priya.subramanian@medical.in',
      district: 'Coimbatore',
      area: 'Ramanathapuram',
      pinCode: '641045',
      currentAddress: 'Plot No. 12, Ramanathapuram, Coimbatore',
      permanentAddress: 'Subramanian Illam, Ramanathapuram, Coimbatore'
    },
    photos: {
      mainProfilePhoto: 'https://images.unsplash.com/photo-1610030469668-93535c17b6b3?auto=format&fit=crop&q=80&w=400&h=400',
      coverPhoto: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&q=80&w=1200&h=400',
      album: ['https://images.unsplash.com/photo-1610030469668-93535c17b6b3?auto=format&fit=crop&q=80&w=400&h=400']
    },
    aboutMe: {
      personality: ['Compassionate', 'Gentle', 'Intellectual', 'Empathetic', 'Observant'],
      interests: ['Pediatric Wellness', 'Bharatanatyam Classical Dance', 'Tamil Nadu Temples', 'Traditional Architecture', 'Gardening'],
      hobbies: ['Photography', 'Reading Fiction', 'Traditional Cooking', 'Traveling', 'Classical Music'],
      lifeGoals: 'To build a top-tier pediatric healthcare practice in Tamil Nadu while raising a family rooted in cultural literacy and values.',
      expectations: 'Seeking an educated Tamil professional or doctor who has high empathy, respects an independent woman\'s career, and enjoys simple family bonding.'
    },
    religiousInfo: {
      templeVisits: 'Frequent visits (regular to Kapaleeshwarar Temple and Marudhamalai Temple)',
      spiritualBeliefs: 'Faith in the divinity of Lord Murugan and Shiva; believes in silent prayer, charity, and selfless service.',
      religiousPractices: 'Celebrates Pongal and Tamil New Year traditionally with home pujas and kolams.'
    },
    educationDetails: {
      highestQualification: 'Doctor of Medicine',
      degree: 'M.D. in Pediatrics',
      specialization: 'Pediatrics & Neonatology',
      college: 'Madras Medical College, Chennai',
      university: 'The Tamil Nadu Dr. M.G.R. Medical University',
      graduationYear: 2023,
      additionalQualifications: ['MBBS from Coimbatore Medical College'],
      certifications: ['IAP Pediatric Advanced Life Support (PALS)'],
      academicAchievements: ['Topper in MBBS Pediatrics module', 'Published research paper in Indian Journal of Pediatrics']
    },
    occupationDetails: {
      employmentType: 'Private Sector',
      occupation: 'Consultant Pediatrician',
      companyName: 'PSG Hospitals, Coimbatore',
      designation: 'Junior Consultant - Pediatrics',
      industry: 'Healthcare / Hospitals',
      experience: '3 Years',
      annualIncome: '₹18 LPA',
      monthlyIncome: '₹1.5 Lakhs',
      officeLocation: 'RS Puram, Coimbatore',
      workingCountry: 'India'
    },
    familyDetails: {
      father: {
        name: 'Gopinathan Subramanian',
        occupation: 'Retired Superintending Engineer',
        education: 'B.Tech Civil Engineering - IIT Madras',
        status: 'Alive'
      },
      mother: {
        name: 'Devika Subramanian',
        occupation: 'Retired High School Headmistress',
        education: 'M.Sc, B.Ed (Physics)',
        status: 'Homemaker'
      },
      siblings: {
        brothers: 1,
        marriedBrothers: 0,
        sisters: 0,
        marriedSisters: 0
      },
      familyType: 'Nuclear',
      familyStatus: 'Middle Class',
      nativePlace: 'Coimbatore, Tamil Nadu',
      familyWealth: 'Ancestral home in Madurai, own house in Coimbatore, savings and deposits.',
      ownHouse: true
    },
    habits: {
      smoking: 'No',
      drinking: 'No',
      fitness: ['Yoga', 'Jogging', 'Dance practice'],
      gym: false,
      yoga: true,
      travel: 'Enjoys exploring lush green hill stations in Wayanad, beaches of Kovalam, and visiting historic spots in India.',
      drivingLicense: true
    },
    physicalAppearance: {
      skinTone: 'Wheatish',
      hairColor: 'Black / Long curly',
      eyeColor: 'Dark Brown',
      bodyType: 'Average'
    },
    assets: {
      ownHouse: true,
      apartment: true,
      villa: false,
      land: true,
      car: 'Maruti Suzuki Baleno',
      investments: 'Fixed Deposits, Gold, Mutual Funds',
      gold: '60 Sovereigns'
    },
    partnerPreferences: {
      ageRange: '28 - 32 Years',
      height: "5'7\" - 6'1\"",
      maritalStatus: 'Never Married',
      religion: 'Hindu',
      caste: 'Pillai',
      subCaste: 'Saiva',
      qualification: 'Masters, Professional Degree, or PG',
      degree: 'MBBS, MD, MS, B.Tech, MBA, MCA',
      occupation: 'Doctor, Engineer, Management, Tech Professional, IAS/IPS',
      income: '₹20 LPA+',
      diet: 'Vegetarian or Non-Vegetarian',
      smoking: 'No',
      drinking: 'No or Occasionally',
      country: 'India (preferably Tamil Nadu)',
      state: 'Tamil Nadu',
      city: 'Chennai, Coimbatore, Madurai, Trichy',
      star: 'Pushya, Anuradha, Aswini, Makha, Hastham',
      rasi: 'Karka, Vrischika, Meena, Kanya',
      dosham: 'No major Dosham'
    },
    aiCompatibility: {
      personalityScore: 88,
      lifestyleMatch: 90,
      familyValuesMatch: 86,
      educationMatch: 94,
      careerMatch: 91,
      horoscopeMatch: 80,
      overallMatch: 88
    },
    verification: {
      mobileVerified: true,
      emailVerified: true,
      aadhaarVerified: true,
      panVerified: true,
      passportVerified: true,
      employmentVerified: true,
      educationVerified: true,
      photoVerified: true
    },
    activity: {
      lastLogin: 'Yesterday',
      onlineStatus: 'Offline',
      profileCompletion: 92,
      profileViews: 215,
      interestsSent: 10,
      interestsReceived: 32,
      shortlistedBy: 40
    },
    premiumFeatures: {
      premiumMember: true
    },
    aiProfileInsights: {
      profileStrength: 'Very High',
      missingInformation: ['A few optional asset and habit details.'],
      suggestedImprovements: ['Add more traditional wear photos in Kerala Kasavu saree.'],
      matchProbability: 'High (85%)',
      compatibilityAnalysis: 'Dr. Priya has a wonderful, high-empathy profile. Her medical career combined with artistic interests in Mohiniyattam makes her compatible with stable professionals who value healthcare careers and respect artistic pursuits.'
    },
    documents: {
      aadhaarCard: true,
      panCard: true,
      passport: true,
      degreeCertificate: true,
      salarySlip: false,
      horoscopePdf: true
    }
  },
  {
    id: 'p4',
    name: 'Adithya Pandian',
    gender: 'Groom',
    age: 30,
    height: "6'0\"",
    religion: 'Hindu',
    caste: 'Nadar',
    subCaste: 'Karkathar',
    motherTongue: 'Tamil',
    profession: 'Investment Banker',
    education: 'B.Tech IIT Madras & MBA ISB',
    location: { city: 'Madurai', state: 'Tamil Nadu', country: 'India' },
    salary: '₹48 LPA',
    diet: 'Non-Veg',
    manglik: 'No',
    horoscopeNeeded: false,
    starSign: 'Libra',
    familyValues: 'Liberal',
    lifestyle: 'Modern',
    bio: 'A passionate, hard-working investment banker who loves classical Tamil literature, playing the flute, and beachside running in Madurai. Grounded in family values, looking for an independent, educated South Indian woman with her own professional ambitions.',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=600&h=600',
    verified: true,
    contactNumber: '+91 97480 98765',
    birthDate: '1996-10-05',
    birthTime: '08:15 PM',
    birthPlace: 'Madurai, Tamil Nadu',
    rashi: 'Tula (Libra)',
    nakshatra: 'Chitra',
    gotra: 'Vishnu',

    basicInfo: {
      profileCreatedBy: 'Self',
      firstName: 'Adithya',
      lastName: 'Pandian',
      displayName: 'Adithya P.',
      weight: '82 kg',
      bodyType: 'Athletic',
      complexion: 'Fair',
      bloodGroup: 'B+ve',
      maritalStatus: 'Never Married',
      children: 'None',
      disabilityStatus: 'None',
      languagesKnown: ['Tamil', 'English', 'Hindi', 'Telugu'],
      nationality: 'Indian',
      citizenship: 'Indian'
    },
    contactInfo: {
      mobileNumber: '+91 97480 98765',
      whatsAppNumber: '+91 97480 98765',
      email: 'adithya.pandian@ibanking.com',
      district: 'Madurai',
      area: 'KK Nagar',
      pinCode: '625020',
      currentAddress: 'Ganga Apartments, KK Nagar, Madurai',
      permanentAddress: 'Ganga Apartments, KK Nagar, Madurai'
    },
    photos: {
      mainProfilePhoto: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=crop&q=80&w=400&h=400',
      coverPhoto: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1200&h=400',
      album: ['https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=crop&q=80&w=400&h=400']
    },
    aboutMe: {
      personality: ['Ambitious', 'Charismatic', 'Progressive', 'Dynamic', 'Outgoing'],
      interests: ['Investment Banking', 'Classical Tamil Sangam Literature', 'Beachside Running', 'Flute Playing', 'Global Travel'],
      hobbies: ['Flute Recitals', 'Marathon Training', 'Reading Business Memoirs', 'Amateur Photography', 'Investments'],
      lifeGoals: 'To lead a major corporate financial practice while establishing charity clinics in Tamil Nadu and leading a progressive, loving family.',
      expectations: 'Looking for a smart, highly educated Tamil or South Indian woman with clear career ambitions, strong modern values, and an open heart.'
    },
    religiousInfo: {
      templeVisits: 'Occasional visits (specifically Madurai Meenakshi Temple during festivals)',
      spiritualBeliefs: 'Mainly spiritual; believes in ethics, kindness, karma, and supporting underprivileged communities.',
      religiousPractices: 'Celebrates Pongal and Tamil New Year with family and conducts charity drives.'
    },
    educationDetails: {
      highestQualification: 'Master of Business Administration',
      degree: 'MBA (PGP)',
      specialization: 'Finance & Investment Banking',
      college: 'Indian School of Business (ISB) Hyderabad & IIT Madras',
      university: 'ISB & IIT Madras',
      graduationYear: 2020,
      additionalQualifications: ['B.Tech in Computer Science from IIT Madras'],
      certifications: ['Financial Risk Manager (FRM)', 'Chartered Financial Analyst (CFA) Charterholder'],
      academicAchievements: ['IIT Joint Entrance Exam Rank under 100', 'Deans Honor List at ISB']
    },
    occupationDetails: {
      employmentType: 'Private Sector',
      occupation: 'Vice President - Investment Banking',
      companyName: 'Goldman Sachs',
      designation: 'VP - Mergers & Acquisitions',
      industry: 'Banking / Financial Services',
      experience: '7 Years',
      annualIncome: '₹48 LPA',
      monthlyIncome: '₹3.8 Lakhs',
      officeLocation: 'Outer Ring Road, Bangalore & Vizag (Hybrid)',
      workingCountry: 'India'
    },
    familyDetails: {
      father: {
        name: 'Prasad Pandian',
        occupation: 'Senior IAS Officer',
        education: 'M.A. Public Administration',
        status: 'Alive'
      },
      mother: {
        name: 'Lakshmi Pandian',
        occupation: 'Associate Professor',
        education: 'Ph.D. in Botany',
        status: 'Working'
      },
      siblings: {
        brothers: 0,
        marriedBrothers: 0,
        sisters: 1,
        marriedSisters: 1
      },
      familyType: 'Nuclear',
      familyStatus: 'Rich / Upper Class',
      nativePlace: 'Guntur, Andhra Pradesh',
      familyWealth: 'Multiple luxury apartments in Hyderabad and Vizag, substantial agricultural estates in Guntur.',
      ownHouse: true
    },
    habits: {
      smoking: 'No',
      drinking: 'Occasionally',
      fitness: ['Gym', 'Flute sessions', 'Long runs'],
      gym: true,
      yoga: false,
      travel: 'Travels extensively worldwide. Visited 15+ countries for leisure and work.',
      drivingLicense: true
    },
    physicalAppearance: {
      skinTone: 'Fair',
      hairColor: 'Black',
      eyeColor: 'Dark Brown',
      beard: true,
      bodyType: 'Athletic'
    },
    assets: {
      ownHouse: true,
      apartment: true,
      villa: true,
      car: 'BMW 3 Series',
      investments: 'High Venture Capital and Stock portfolios',
      savings: 'Very High'
    },
    partnerPreferences: {
      ageRange: '25 - 29 Years',
      height: "5'4\" - 5'10\"",
      maritalStatus: 'Never Married',
      religion: 'Hindu',
      caste: 'Naidu or Reddy or any South Indian',
      subCaste: 'Any',
      qualification: 'Bachelors or Masters Degree',
      degree: 'B.Tech, M.S, MBA, MD, MBBS, Law, or equivalent',
      occupation: 'Tech, Banking, Consulting, Medicine, Design, or Research',
      income: '₹12 LPA+',
      diet: 'No restriction',
      smoking: 'No',
      drinking: 'No or Occasionally',
      country: 'India or USA',
      state: 'Andhra Pradesh, Telangana, Karnataka, Tamil Nadu',
      city: 'Hyderabad, Vizag, Bangalore, Chennai, USA cities',
      star: 'Any',
      rasi: 'Any',
      dosham: 'No preference'
    },
    aiCompatibility: {
      personalityScore: 90,
      lifestyleMatch: 94,
      familyValuesMatch: 84,
      educationMatch: 95,
      careerMatch: 94,
      horoscopeMatch: 75,
      overallMatch: 89
    },
    verification: {
      mobileVerified: true,
      emailVerified: true,
      aadhaarVerified: true,
      panVerified: true,
      passportVerified: true,
      employmentVerified: true,
      educationVerified: true,
      photoVerified: true
    },
    activity: {
      lastLogin: 'Today, 08:30 AM',
      onlineStatus: 'Recent',
      profileCompletion: 94,
      profileViews: 412,
      interestsSent: 30,
      interestsReceived: 75,
      shortlistedBy: 88
    },
    premiumFeatures: {
      premiumMember: true,
      profileBoost: false,
      spotlightProfile: true
    },
    aiProfileInsights: {
      profileStrength: 'Very High',
      missingInformation: ['A few document uploads.'],
      suggestedImprovements: ['Upload degree certificate for complete educational badge verification.'],
      matchProbability: 'Very High (89%)',
      compatibilityAnalysis: 'Aditya is an elite candidate with stellar academic credentials (IIT/ISB) and high income. His modern lifestyle preferences indicate maximum compatibility with progressive, self-driven women in major tech-cities.'
    },
    documents: {
      aadhaarCard: true,
      panCard: true,
      passport: true,
      degreeCertificate: false,
      salarySlip: true,
      horoscopePdf: false
    }
  },
  {
    id: 'p5',
    name: 'Meera Pillai',
    gender: 'Bride',
    age: 25,
    height: "5'2\"",
    religion: 'Hindu',
    caste: 'Pillai',
    subCaste: 'Saiva',
    motherTongue: 'Tamil',
    profession: 'Chartered Accountant',
    education: 'CA (Rank Holder)',
    location: { city: 'Chennai', state: 'Tamil Nadu', country: 'India' },
    salary: '₹16 LPA',
    diet: 'Veg',
    manglik: 'No',
    horoscopeNeeded: true,
    starSign: 'Virgo',
    familyValues: 'Traditional',
    lifestyle: 'Balanced',
    bio: 'Grounded and detail-oriented CA working at a top firm in Chennai. Enjoy Carnatic vocal singing, kolam designing, temple visits, and culinary arts. Seeking a traditional Tamil Brahmin or Pillai partner who holds deep-seated moral values.',
    image: 'https://images.unsplash.com/photo-1607190074257-dd4b7af0309f?auto=format&fit=crop&q=80&w=400&h=400',
    verified: true,
    contactNumber: '+91 94440 12345'
  },
  {
    id: 'p6',
    name: 'Vikram Selvam',
    gender: 'Groom',
    age: 29,
    height: "5'10\"",
    religion: 'Hindu',
    caste: 'Gounder',
    subCaste: 'Kongu Gounder',
    motherTongue: 'Tamil',
    profession: 'Business Owner',
    education: 'B.S. in Industrial Engineering (USA)',
    location: { city: 'Coimbatore', state: 'Tamil Nadu', country: 'India' },
    salary: '₹60 LPA (Business profit)',
    diet: 'Non-Veg',
    manglik: 'Anshik',
    horoscopeNeeded: true,
    starSign: 'Scorpio',
    familyValues: 'Moderate',
    lifestyle: 'Modern',
    bio: 'Running a successful family enterprise in Coimbatore. Tech enthusiast, fitness lover, and amateur chef of spicy Chettinad cuisine. Seeking a cheerful, smart partner with whom I can share life\'s grand journeys and traditional celebrations.',
    image: 'https://images.unsplash.com/photo-1618015358954-115ef1ed6515?auto=format&fit=crop&q=80&w=400&h=400',
    verified: true,
    contactNumber: '+91 90000 98765'
  },
  {
    id: 'p7',
    name: 'Kavya Rajan',
    gender: 'Bride',
    age: 28,
    height: "5'6\"",
    religion: 'Hindu',
    caste: 'Chettiar',
    subCaste: 'Devanga',
    motherTongue: 'Tamil',
    profession: 'Fashion Designer',
    education: 'B.Des from NIFT Bengaluru',
    location: { city: 'Tiruchirappalli', state: 'Tamil Nadu', country: 'India' },
    salary: '₹14 LPA',
    diet: 'Eggetarian',
    manglik: 'Manglik',
    horoscopeNeeded: true,
    starSign: 'Sagittarius',
    familyValues: 'Moderate',
    lifestyle: 'Modern',
    bio: 'Creative soul with a passion for South Indian handloom silk heritage (Kanchipuram Silk) and modern silhouettes. Love painting, visiting historic temples, and classical instrumental music. Looking for a progressive Tamil-based partner who appreciates art and family values.',
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=400&h=400',
    verified: true,
    contactNumber: '+91 95555 43210'
  },
  {
    id: 'p8',
    name: 'Arjun Madhavan',
    gender: 'Groom',
    age: 31,
    height: "5'9\"",
    religion: 'Hindu',
    caste: 'Chettiar',
    subCaste: 'Devanga',
    motherTongue: 'Tamil',
    profession: 'Senior Data Scientist',
    education: 'Ph.D. in Statistics - IISc Bangalore',
    location: { city: 'Madurai', state: 'Tamil Nadu', country: 'India' },
    salary: '₹28 LPA',
    diet: 'Veg',
    manglik: 'No',
    horoscopeNeeded: false,
    starSign: 'Taurus',
    familyValues: 'Liberal',
    lifestyle: 'Balanced',
    bio: 'Senior Data Scientist and nature hiker originally from Madurai, now in Chennai. I love solving data puzzles, playing veena, and cooking traditional South Indian vegetarian delicacies. Seeking a thoughtful, intellectual partner who values deep conversation and cultural traditions.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600&h=600',
    verified: true,
    contactNumber: '+91 88888 77777'
  },
  {
    id: 'p9',
    name: 'Shruti Srinivasan',
    gender: 'Bride',
    age: 25,
    height: "5'3\"",
    religion: 'Hindu',
    caste: 'Brahmin',
    subCaste: 'Vadakalai',
    motherTongue: 'Tamil',
    profession: 'UI/UX Designer',
    education: 'B.Des - IIT Bombay',
    location: { city: 'Chennai', state: 'Tamil Nadu', country: 'India' },
    salary: '₹18 LPA',
    diet: 'Veg',
    manglik: 'Non-Manglik',
    horoscopeNeeded: true,
    starSign: 'Virgo',
    familyValues: 'Moderate',
    lifestyle: 'Balanced',
    bio: 'Creative and warm Tamil Iyengar Brahmin UI/UX designer. Passionate about Carnatic classical music, traditional cooking, and sketching. Seeking a companion who is career-oriented yet holds traditional value systems.',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600&h=600',
    verified: true,
    contactNumber: '+91 94444 88888'
  },
  {
    id: 'p10',
    name: 'Adithya Raghavan',
    gender: 'Groom',
    age: 29,
    height: "5'11\"",
    religion: 'Hindu',
    caste: 'Brahmin',
    subCaste: 'Vadama',
    motherTongue: 'Tamil',
    profession: 'Software Architect',
    education: 'M.Tech - IISc Bangalore',
    location: { city: 'Chennai', state: 'Tamil Nadu', country: 'India' },
    salary: '₹42 LPA',
    diet: 'Veg',
    manglik: 'Non-Manglik',
    horoscopeNeeded: true,
    starSign: 'Leo',
    familyValues: 'Traditional',
    lifestyle: 'Balanced',
    bio: 'Pragmatic and down-to-earth software architect based in Chennai, originally from Thanjavur, Tamil Nadu. Enjoy exploring Vedic culture, hiking, playing veena, and visiting spiritual places. Looking for an understanding partner who values family roots and has a progressive lifestyle.',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600&h=600',
    verified: true,
    contactNumber: '+91 92222 77777'
  }
];

export const successStories: SuccessStory[] = [
  {
    id: 's1',
    coupleName: 'Ananth & Shalini',
    weddingDate: 'Nov 12, 2025',
    story: 'We met on Vedic Matrimony through the AI compatibility matcher. Our shared love for Carnatic music, filter coffee, and temple trails in Tanjore resonated perfectly. After an AI compatibility match of 94%, we decided to meet in Chennai, and our families instantly agreed. Truly a divine alignment!',
    image: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    location: 'Chennai, Tamil Nadu'
  },
  {
    id: 's2',
    coupleName: 'Hari & Meenakshi',
    weddingDate: 'Feb 18, 2026',
    story: 'Our horoscopes had an exceptional 31 out of 36 Poruthams (Gunas). Being from Chennai but settled in Bengaluru, we wanted to bridge traditional expectations with modern lifestyles. Our wedding in Madurai was a gorgeous, traditional event with Nadaswaram music and beautiful Kanjeevaram silks.',
    image: 'https://images.unsplash.com/photo-1607190074257-dd4b7af0309f?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    location: 'Madurai, Tamil Nadu'
  },
  {
    id: 's3',
    coupleName: 'Karthik & Lakshmi',
    weddingDate: 'April 05, 2026',
    story: 'Both of us were living in the USA, looking for partners with deep South Indian traditional roots. We connected online, verified our families via the Family Verified program, and flew back to India for our traditional wedding in Madurai. Extremely satisfied with the safety and premium feel of this application.',
    image: 'https://images.unsplash.com/photo-1621616875450-79f22448040e?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    location: 'Madurai, Tamil Nadu'
  }
];

export const blogArticles: BlogArticle[] = [
  {
    id: 'b1',
    title: 'Modern Jadhaga Porutham: Balancing Stars & Shared Values',
    excerpt: 'Explore how traditional Jadhaga Porutham (horoscope matching) can be combined with modern compatibility tests for a strong marriage foundation.',
    category: 'Horoscope',
    author: 'Acharya Dr. R. K. Shastri',
    readTime: '5 min read',
    date: 'July 10, 2026',
    content: 'Historically, South Indian marriages placed immense weight on the 10/11 Poruthams (astrological parameters). Today, enlightened couples understand that spiritual harmony goes hand-in-hand with emotional maturity, professional respect, and intellectual alignment. Modern Jadhaga Porutham evaluates astronomical alignment alongside psychological parameters to predict relationship resilience in our dynamic society.',
    image: 'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'b2',
    title: 'Healthy Communication Rules for Matrimonial Matches',
    excerpt: 'Tips on how to approach your first chat on a matrimonial platform with elegance, respect, and interest.',
    category: 'Relationship',
    author: 'Sunita Mehra (Relationship Counselor)',
    readTime: '4 min read',
    date: 'June 25, 2026',
    content: 'The initial communication sets the tone of your matrimonial interaction. Always start with a warm greeting, ask about their hobbies, and explain your own life outlook honestly. Avoid asking intrusive personal or financial questions too early. Focus instead on uncovering mutual values, alignment on lifestyle choices, and family relationships.',
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'b3',
    title: 'Top 5 Sacred Rituals of a Hindu Wedding & Their Meanings',
    excerpt: 'A deep dive into the spiritual meaning behind Saptapadi, Kanyadaan, Sindoor, and other beautiful Vedic wedding customs.',
    category: 'Tradition',
    author: 'Prof. Suresh Kumar',
    readTime: '6 min read',
    date: 'May 18, 2026',
    content: 'A Hindu wedding is more than a social contract; it is a sacred sanskara (sacrament) binding two souls for seven lifetimes. Saptapadi, or the seven sacred vows taken around the holy fire, forms the legal and spiritual climax of the wedding. Each vow binds the couple to support one another in duties, health, children, and spiritual goals.',
    image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&q=80&w=800'
  }
];
